---
# tasks file for curl

- name: Sleep for 5 seconds and continue with play
  wait_for:
    timeout: 5

- name: Check that you can connect (GET) to a page and it returns a status 200
  uri:
    url: http://192.168.145.100:80
    return_content: yes
  register: output

- name: curl message from webserver
  debug:
    msg: "the server at {{ output.url }}, returned status code {{ output.status }} with content {{ output.content }}"