---
- hosts: webservers
  become: true
  vars_files:
    vars.yaml
  tasks:  
    
    - name: create new index.html file
      lineinfile:
        create: yes
        path: /var/www/html/index.html
        line: <html> "Hello World" </html>


    - name: start apache
      service: 
        name: apache2 
        state: started