---
# tasks file for jinja

- name: delete original index.html file
  file: 
    path: /var/www/html/index.html 
    state: absent
  tags: jinja

- name: create new index.html file
  lineinfile:
    create: yes
    path: /var/www/html/index.html
    line: "{% if addresses|length > 10 %}
            <html>Will not Print</html>

          {% elif addresses|length > 1 %}
            <html>
            {% for address in addresses %}
              <li>{{ address }}</li>
            {% endfor %}
            </html>
          {% endif %}"
  tags: jinja
        

- name: start apache
  service: 
    name: apache2 
    state: started
  tags: jinja